### ISSUE TITLE
Структура репозитория

### ISSUE THREAD

**Issue by causer** [dmitriyse/ClrCoder#1]
Привет. Сейчас модная такая структура репозитория:
- в корне лежат файлы .sln, .gitignore, setting, licence, build.cmd и т.д.
/src - проекты солюшена
/test - проекты тестов (именно test, без 's' на конце)

Можно на MS ориентироваться.
https://github.com/aspnet/dnx

**Comment by dmitriyse** [comment]
You are right. I will change project files layout.

**Comment by causer** [comment]
I have found good post about repository layout.
https://gist.github.com/davidfowl/ed7564297c61fe9ab814

**Comment by dmitriyse** [comment]
We will use structure suggested in the ClrCoder.Starship project.
