### ISSUE TITLE
Support CoreCLR?

### ISSUE THREAD

**Issue by causer** [dmitriyse/ClrCoder#2]
Hi, Do you have any plans to support coreclr?

**Comment by dmitriyse** [comment]
Sure, but not for now. I am waiting DNX RTM and R# support (JetBrains.Annotations nuget package).

**Comment by dmitriyse** [comment]
ClrCore now can be build and tested on Windows, Mono/Linux, CoreCLR.
Compatibility level: .NETStandard 1.1, PCL Profile111
